// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuxntipzwabwdywsaptj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1eG50aXB6d2Fid2R5d3NhcHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NTAzMjAsImV4cCI6MjA3NTQyNjMyMH0.QM1glSQ2WfIb1U8hXLh8GXnfEBAApwmO1gbbO605JYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});